project:
  type: website

website:
  google-analytics: "G-VVFCV6MNHG"
  title: "ISSS624"
  navbar:
    left: 
      - text: References & Notes
        menu:
          - text: Extra In-Class 1
            href: personal_note/is415_l1/is415_l1.qmd 
          - text: Extra In-Class 2
            href: personal_note/is415_l2/is415_l2.qmd 
          - text: Extra In-Class 4
            href: personal_note/is415_l4/is415_l4.qmd
          - text: Extra In-Class 5
            href: personal_note/is415_l5/is415_l5.qmd
          - text: Acronym & Terminology
            href: personal_note/Acronym_Terminology.qmd
          - text: Common Errors and Basic Concepts
            href: personal_note/Personal_notes.qmd
          - text: Spatial Autocorrelation & Spatial Dependency  
            href: personal_note/SpatialAutocorrelationSpatialDependency.qmd
          - text: Spatially Constrained Cluster Analysis 
            href: personal_note/SpatialConstrainedClusterAnalysis.qmd
          - text: Geographically Weighted Logistic Regres
            href: personal_note/gwlr.qmd
          - text: Functions & Arguments
            href: personal_note/func_arg.qmd            
            
      - text: Hands-on Exercises
        menu: 
          - text: Geospatial Data Wrangling with R [1]
            href: Hands-on_Ex1-1.qmd
          - text: Choropleth Mapping with R [2]
            href: Hands-on_Ex1-2.qmd
          - text: Global & Local Measures of Spatial Autocorrelation [4]
            href: Hands-on_Ex2-4.qmd  
          - text: Spatially Constrained Clustering Techniques [5]
            href: Hands-on_Ex3-5.qmd
          - text: Geographically Weighted Regression [6]
            href: Hands-on_Ex4-6.qmd  
            
      - text: In-class Exercises
        menu: 
          - text: Spatial Weights & Applications [3]
            href: in-class_ex/in-class_ex1/In-class_Ex1.qmd
          - text: In-class Exercise 2 - Case Study 1.1 Spatial Autocorrelation
            href: in-class_ex/in-class_ex2/In-class_Ex2.qmd
          - text: In-class Exercise 3 - Case Study 1.2 Clustering Analysis
            href: in-class_ex/in-class_ex3/In-class_Ex3.qmd
          - text: In-class Exercise 4 - Case Study 2.1 Geographically Weighted Regression
            href: in-class_ex/in-class_ex4/In-class_Ex4.qmd
          - text: In-class Exercise 5 - Case Study 2.2 GWLR
            href: in-class_ex/in-class_ex5/In-class_Ex5.qmd  


      - text: Projects
        menu: 
          - text: Class Project 1 - Spatial Weights & Applications
            href: class_project/project_1/spatial_weights.qmd
          - text: Class Project 2 - Regionalisation with Spatially Constrained Cluster Analysis
            href: class_project/project_2/Regionalisation_scca_v3.1.qmd
          - text: Exploration 1 - Rehabilated Non-Functional Water Points in Nigeria
            href: exploration/exploration_1/exp1_rehabilitated_wpt.qmd
          - text: Exploration 2 - Thematic Mapping Water Points in Nigeria
            href: exploration/exploration_2/exp2_thematic_mapping.qmd
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

